// Copyright 2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/** Autogenerated using the write_signals.py script, do not edit. */

#include <stdint.h>

#if 0

#elif (BASE == 48000) && (MULT == 512) && (TEST_FREQ == 1000)
extern uint32_t signal_48000_512_1000[76800];
#define sig signal_48000_512_1000

#elif (BASE == 44100) && (MULT == 512) && (TEST_FREQ == 1000)
extern uint32_t signal_44100_512_1000[70560];
#define sig signal_44100_512_1000

#elif (BASE == 48000) && (MULT == 256) && (TEST_FREQ == 1000)
extern uint32_t signal_48000_256_1000[38400];
#define sig signal_48000_256_1000

#elif (BASE == 44100) && (MULT == 256) && (TEST_FREQ == 1000)
extern uint32_t signal_44100_256_1000[35280];
#define sig signal_44100_256_1000

#elif (BASE == 48000) && (MULT == 128) && (TEST_FREQ == 1000)
extern uint32_t signal_48000_128_1000[38400];
#define sig signal_48000_128_1000

#elif (BASE == 44100) && (MULT == 128) && (TEST_FREQ == 1000)
extern uint32_t signal_44100_128_1000[35280];
#define sig signal_44100_128_1000

#elif (BASE == 48000) && (MULT == 64) && (TEST_FREQ == 1000)
extern uint32_t signal_48000_64_1000[19200];
#define sig signal_48000_64_1000

#elif (BASE == 44100) && (MULT == 64) && (TEST_FREQ == 1000)
extern uint32_t signal_44100_64_1000[17640];
#define sig signal_44100_64_1000

#elif (BASE == 48000) && (MULT == 512) && (TEST_FREQ == 2000)
extern uint32_t signal_48000_512_2000[76800];
#define sig signal_48000_512_2000

#elif (BASE == 44100) && (MULT == 512) && (TEST_FREQ == 2000)
extern uint32_t signal_44100_512_2000[70560];
#define sig signal_44100_512_2000

#elif (BASE == 48000) && (MULT == 256) && (TEST_FREQ == 2000)
extern uint32_t signal_48000_256_2000[38400];
#define sig signal_48000_256_2000

#elif (BASE == 44100) && (MULT == 256) && (TEST_FREQ == 2000)
extern uint32_t signal_44100_256_2000[35280];
#define sig signal_44100_256_2000

#elif (BASE == 48000) && (MULT == 128) && (TEST_FREQ == 2000)
extern uint32_t signal_48000_128_2000[38400];
#define sig signal_48000_128_2000

#elif (BASE == 44100) && (MULT == 128) && (TEST_FREQ == 2000)
extern uint32_t signal_44100_128_2000[35280];
#define sig signal_44100_128_2000

#elif (BASE == 48000) && (MULT == 64) && (TEST_FREQ == 2000)
extern uint32_t signal_48000_64_2000[19200];
#define sig signal_48000_64_2000

#elif (BASE == 44100) && (MULT == 64) && (TEST_FREQ == 2000)
extern uint32_t signal_44100_64_2000[17640];
#define sig signal_44100_64_2000

#elif (BASE == 48000) && (MULT == 512) && (TEST_FREQ == 4000)
extern uint32_t signal_48000_512_4000[76800];
#define sig signal_48000_512_4000

#elif (BASE == 44100) && (MULT == 512) && (TEST_FREQ == 4000)
extern uint32_t signal_44100_512_4000[70560];
#define sig signal_44100_512_4000

#elif (BASE == 48000) && (MULT == 256) && (TEST_FREQ == 4000)
extern uint32_t signal_48000_256_4000[38400];
#define sig signal_48000_256_4000

#elif (BASE == 44100) && (MULT == 256) && (TEST_FREQ == 4000)
extern uint32_t signal_44100_256_4000[35280];
#define sig signal_44100_256_4000

#elif (BASE == 48000) && (MULT == 128) && (TEST_FREQ == 4000)
extern uint32_t signal_48000_128_4000[38400];
#define sig signal_48000_128_4000

#elif (BASE == 44100) && (MULT == 128) && (TEST_FREQ == 4000)
extern uint32_t signal_44100_128_4000[35280];
#define sig signal_44100_128_4000

#elif (BASE == 48000) && (MULT == 64) && (TEST_FREQ == 4000)
extern uint32_t signal_48000_64_4000[19200];
#define sig signal_48000_64_4000

#elif (BASE == 44100) && (MULT == 64) && (TEST_FREQ == 4000)
extern uint32_t signal_44100_64_4000[17640];
#define sig signal_44100_64_4000

#elif (BASE == 48000) && (MULT == 512) && (TEST_FREQ == 8000)
extern uint32_t signal_48000_512_8000[76800];
#define sig signal_48000_512_8000

#elif (BASE == 44100) && (MULT == 512) && (TEST_FREQ == 8000)
extern uint32_t signal_44100_512_8000[70560];
#define sig signal_44100_512_8000

#elif (BASE == 48000) && (MULT == 256) && (TEST_FREQ == 8000)
extern uint32_t signal_48000_256_8000[38400];
#define sig signal_48000_256_8000

#elif (BASE == 44100) && (MULT == 256) && (TEST_FREQ == 8000)
extern uint32_t signal_44100_256_8000[35280];
#define sig signal_44100_256_8000

#elif (BASE == 48000) && (MULT == 128) && (TEST_FREQ == 8000)
extern uint32_t signal_48000_128_8000[38400];
#define sig signal_48000_128_8000

#elif (BASE == 44100) && (MULT == 128) && (TEST_FREQ == 8000)
extern uint32_t signal_44100_128_8000[35280];
#define sig signal_44100_128_8000

#elif (BASE == 48000) && (MULT == 64) && (TEST_FREQ == 8000)
extern uint32_t signal_48000_64_8000[19200];
#define sig signal_48000_64_8000

#elif (BASE == 44100) && (MULT == 64) && (TEST_FREQ == 8000)
extern uint32_t signal_44100_64_8000[17640];
#define sig signal_44100_64_8000

#elif (BASE == 48000) && (MULT == 512) && (TEST_FREQ == 19997)
extern uint32_t signal_48000_512_19997[76800];
#define sig signal_48000_512_19997

#elif (BASE == 44100) && (MULT == 512) && (TEST_FREQ == 19997)
extern uint32_t signal_44100_512_19997[70560];
#define sig signal_44100_512_19997

#elif (BASE == 48000) && (MULT == 256) && (TEST_FREQ == 19997)
extern uint32_t signal_48000_256_19997[38400];
#define sig signal_48000_256_19997

#elif (BASE == 44100) && (MULT == 256) && (TEST_FREQ == 19997)
extern uint32_t signal_44100_256_19997[35280];
#define sig signal_44100_256_19997

#elif (BASE == 48000) && (MULT == 128) && (TEST_FREQ == 19997)
extern uint32_t signal_48000_128_19997[38400];
#define sig signal_48000_128_19997

#elif (BASE == 44100) && (MULT == 128) && (TEST_FREQ == 19997)
extern uint32_t signal_44100_128_19997[35280];
#define sig signal_44100_128_19997

#elif (BASE == 48000) && (MULT == 64) && (TEST_FREQ == 19997)
extern uint32_t signal_48000_64_19997[19200];
#define sig signal_48000_64_19997

#elif (BASE == 44100) && (MULT == 64) && (TEST_FREQ == 19997)
extern uint32_t signal_44100_64_19997[17640];
#define sig signal_44100_64_19997

#else
#error "Signal is not set up for this config"
#endif
